# This is the settings file, which you can use to control the behavior of 
# the server

host: '0.0.0.0'
port: 5000
password: 'password'
debug_mode: true
log_file: 'hack_gms_log.log'
log_level: 'DEBUG'

